[tool.poetry]
name = "fastapicrud1"
version = "0.1.0"
description = ""
authors = ["Ikramali <ikramaliambaliyasana2030@gmil.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
